### ISSUE TITLE
Admin 的Java端错误日志 导致无法运行

### ISSUE THREAD

**Issue by rickiewang** [fingerchar/fingernft#51]
在跑Admin后端的时候发生了一些错误日志,它是这样的:
2022-03-19 11:21:19,434 ERROR [Dapp-Scheduler-2] com.fingerchar.task.NftEventTask [NftEventTask.java : 83] nft event task error
java.lang.NullPointerException: null
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:110)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$0(NftDappEventUtils.java:98)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$1(NftDappEventUtils.java:92)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:91)
	at com.fingerchar.task.NftEventTask.startProcessEvent(NftEventTask.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-03-19 11:21:30,006 ERROR [Dapp-Scheduler-1] com.fingerchar.task.NftEventTask [NftEventTask.java : 83] nft event task error
java.lang.NullPointerException: null
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:110)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$0(NftDappEventUtils.java:98)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$1(NftDappEventUtils.java:92)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:91)
	at com.fingerchar.task.NftEventTask.startProcessEvent(NftEventTask.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-03-19 11:21:42,428 ERROR [Dapp-Scheduler-2] com.fingerchar.task.NftEventTask [NftEventTask.java : 83] nft event task error
java.lang.NullPointerException: null
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:110)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$0(NftDappEventUtils.java:98)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$1(NftDappEventUtils.java:92)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:91)
	at com.fingerchar.task.NftEventTask.startProcessEvent(NftEventTask.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-03-19 11:21:55,105 ERROR [Dapp-Scheduler-3] com.fingerchar.task.NftEventTask [NftEventTask.java : 83] nft event task error
java.lang.NullPointerException: null
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:110)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$0(NftDappEventUtils.java:98)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$1(NftDappEventUtils.java:92)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:91)
	at com.fingerchar.task.NftEventTask.startProcessEvent(NftEventTask.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-03-19 11:22:07,103 ERROR [Dapp-Scheduler-5] com.fingerchar.task.NftEventTask [NftEventTask.java : 83] nft event task error
java.lang.NullPointerException: null
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:110)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$0(NftDappEventUtils.java:98)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.lambda$decodeLog$1(NftDappEventUtils.java:92)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at com.fingerchar.utils.NftDappEventUtils.decodeLog(NftDappEventUtils.java:91)
	at com.fingerchar.task.NftEventTask.startProcessEvent(NftEventTask.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
--------------------------------------------------------------------------------------------------------------------------------------------------------------
我不知道它是如何产生的,是哪里出的问题,或者是我的打包环境问题,他缺少什么吗?谢谢!

**Comment by Ximcxccc** [comment]
你好方便留一下联系方式吗

**Comment by rickiewang** [comment]
/nft-admin/src/main/java/com/fingerchar/task/PayTokenTask.java

**Comment by rickiewang** [comment]
//private static final String _URL = "https://api.coincap.io/v2/rates/binance-coin";
	private static final String _URL = "https://dncapi.bqiapp.com/api/coin/web-coinrank";
请问这个api有替换的吗
