### ISSUE TITLE
create NFT721 error Unknown Error: invalid project id

### ISSUE THREAD

**Issue by Funny-dot** [fingerchar/fingernft#58]
create NFT721 error Unknown Error: invalid project id?
这是啥意思啊

**Comment by surfboy2000** [comment]
同样遇到，再次deploy，发现错误

Error: PollingBlockTracker - encountered an error while attempting to update latest block:
undefined
    at PollingBlockTracker._performSync (/Users/wendy/Desktop/uniquenft/fingernft-main/nft-contract/node_modules/eth-block-tracker/src/polling.js:51:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Emitted 'error' event on Web3ProviderEngine instance at:
    at safeApply (/Users/wendy/Desktop/uniquenft/fingernft-main/nft-contract/node_modules/safe-event-emitter/index.js:70:5)
    at PollingBlockTracker.SafeEventEmitter.emit (/Users/wendy/Desktop/uniquenft/fingernft-main/nft-contract/node_modules/safe-event-emitter/index.js:56:5)
    at PollingBlockTracker._performSync (/Users/wendy/Desktop/uniquenft/fingernft-main/nft-contract/node_modules/eth-block-tracker/src/polling.js:53:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by fingerchar** [comment]
这是scripts/config.js文件配置错误导致的，我们正在优化代码，通过后台操作部署合约

**Comment by MohamedRefaat8816** [comment]
> This is caused by a misconfiguration of the scripts/config.js file, we are optimizing the code and deploying the contract through background operations

Hello I Need esey way to contact you to buy script please send me mail on kokococo27@gmail.com

**Comment by aikangkang** [comment]
请问现在有办法解决了吗？
