### ISSUE TITLE
部署合约报错

### ISSUE THREAD

**Issue by CtyptoIng** [fingerchar/fingernft#60]
$ sudo node deploy.js
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '/Users/Documents/fingernft-main/nft-contract/deploy.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by CtyptoIng** [comment]
已解决

**Comment by hsyndeniz** [comment]
@CtyptoIng I get this error when I run node deploy.js What's wrong?

**Comment by hsyndeniz** [comment]
I used ubuntu and it worked.
